"""
Single place where the scripts find their inputs and put their outputs, so every script runs from any
working directory.

  data/     the Data in Brief deposit (CORA.RDR, DOI 10.34810/DATA3672), unzipped here. Only
            data/processed/participants.csv and data/processed/games.csv are read (the wealth
            treatment is a game-level variable). Override the location with the XAIRE_DATA variable.
  work/     intermediate files generated by the pipeline (lookup tables, synthetic runs, summaries)
  results/  tables and figures generated by the pipeline
work/ and results/ are created on demand and are not tracked by git.
"""
import os
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DATA = Path(os.environ.get("XAIRE_DATA", ROOT / "data"))
PARTICIPANTS = DATA / "processed" / "participants.csv"
GAMES = DATA / "processed" / "games.csv"
WORK = ROOT / "work"
RESULTS = ROOT / "results"
REFERENCE = ROOT / "reference"
for _d in (WORK, RESULTS):
    _d.mkdir(exist_ok=True)

ROUND_COLS = [f"R{i}" for i in range(1, 11)]
NEEDED = ["id", "partida_id", "endowment_initial", "endowment_current",
          "contributed_public_goods", "winnings_public_goods", "goal_reached"] + ROUND_COLS
GAMES_PER_TREATMENT = {"EQUAL": 6, "UNEQUAL-L": 27, "UNEQUAL-H": 44}
ENDOWMENTS = {"EQUAL": {40}, "UNEQUAL-L": {24, 48}, "UNEQUAL-H": {30, 60}}


def load_participants():
    """The cleaned participant file of the deposit (six-player games only), with integrity checks."""
    for f in (PARTICIPANTS, GAMES):
        if not f.exists():
            raise SystemExit(
                f"Missing {f}\nDownload the Data in Brief deposit from CORA.RDR "
                "(DOI 10.34810/DATA3672), unzip it, and copy its contents into data/ "
                "(so that data/processed/participants.csv exists), or set XAIRE_DATA.")
    df = pd.read_csv(PARTICIPANTS)
    missing = [c for c in NEEDED if c not in df.columns]
    if missing:
        raise SystemExit(f"participants.csv lacks expected columns: {missing}")
    if "control_wealth" not in df.columns:      # in the deposit it is stored per game
        games = pd.read_csv(GAMES)[["id", "control_wealth"]].rename(columns={"id": "partida_id"})
        df = df.merge(games, on="partida_id", how="left", validate="many_to_one")
    if df["control_wealth"].isna().any():
        raise SystemExit("Some participants have no wealth treatment (partida_id not found in games.csv).")
    for t, e in ENDOWMENTS.items():
        got = set(df.loc[df["control_wealth"] == t, "endowment_initial"])
        if got != e:
            raise SystemExit(f"Treatment {t} has endowments {sorted(got)}, expected {sorted(e)}.")
    df[ROUND_COLS] = df[ROUND_COLS].astype(float)
    n_games = df.groupby("control_wealth")["partida_id"].nunique().to_dict()
    if len(df) != 462 or df["partida_id"].nunique() != 77 or n_games != GAMES_PER_TREATMENT:
        raise SystemExit(f"Unexpected deposit contents: {len(df)} participants, "
                         f"{df['partida_id'].nunique()} games, games per treatment {n_games}; "
                         "expected 462, 77 and {EQUAL: 6, UNEQUAL-L: 27, UNEQUAL-H: 44}.")
    return df
